[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/api/markers.csv"
  to = "https://raw.githubusercontent.com/AlimanIrawan/indonesia-map-feishu-integration/main/public/markers.csv"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/markers.csv"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/csv"

[[headers]]
  for = "/markers.csv"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/csv" 