[build]
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"
  base = "./"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://raw.githubusercontent.com/AlimanIrawan/indonesia-map-feishu-integration/main/public/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200