services:
  - type: web
    name: feishu-github-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node feishu-proxy-server.js
    rootDir: ./
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # GITHUB_TOKEN 需要在Render控制台手动设置 