services:
  - type: web
    name: indonesia-map-feishu-integration
    env: node
    plan: free
    buildCommand: cd feishu-webhook-server && npm install
    startCommand: cd feishu-webhook-server && npm start
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_TOKEN
        generateValue: true 