services:
  - type: web
    name: indonesia-map-feishu-service
    env: node
    region: singapore
    plan: free
    buildCommand: cd feishu-webhook-server && npm install
    startCommand: cd feishu-webhook-server && node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: API_TOKEN
        value: your-super-secret-token-12345
      - key: NODE_ENV
        value: production 