name: 更新飞书数据到地图CSV

on:
  repository_dispatch:
    types: [feishu-data-update]

jobs:
  update-csv:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 设置Git用户信息
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: 处理飞书推送的数据
      run: |
        echo "收到飞书数据推送"
        echo "数据内容: ${{ toJson(github.event.client_payload) }}"
        
        # 提取数据字段
        SHOP_CODE="${{ github.event.client_payload.shop_code }}"
        LATITUDE="${{ github.event.client_payload.latitude }}"
        LONGITUDE="${{ github.event.client_payload.longitude }}"
        OUTLET_NAME="${{ github.event.client_payload.outlet_name }}"
        BRAND="${{ github.event.client_payload.brand }}"
        KECAMATAN="${{ github.event.client_payload.kecamatan }}"
        POTENSI="${{ github.event.client_payload.potensi }}"
        
        # 检查必要字段
        if [ -z "$SHOP_CODE" ] || [ -z "$LATITUDE" ] || [ -z "$LONGITUDE" ]; then
          echo "❌ 错误：缺少必要字段 shop_code, latitude, longitude"
          exit 1
        fi
        
        echo "✅ 数据验证通过"
        echo "店铺代码: $SHOP_CODE"
        echo "纬度: $LATITUDE"
        echo "经度: $LONGITUDE"
        echo "店铺名称: $OUTLET_NAME"
        echo "品牌: $BRAND"
        echo "区域: $KECAMATAN"
        
    - name: 更新CSV文件
      run: |
        # 确保CSV文件存在
        if [ ! -f "public/markers.csv" ]; then
          echo "shop_code,latitude,longitude,outlet name,brand,kecamatan,potensi" > public/markers.csv
          echo "📝 创建新的CSV文件"
        fi
        
        # 提取数据
        SHOP_CODE="${{ github.event.client_payload.shop_code }}"
        LATITUDE="${{ github.event.client_payload.latitude }}"
        LONGITUDE="${{ github.event.client_payload.longitude }}"
        OUTLET_NAME="${{ github.event.client_payload.outlet_name }}"
        BRAND="${{ github.event.client_payload.brand }}"
        KECAMATAN="${{ github.event.client_payload.kecamatan }}"
        POTENSI="${{ github.event.client_payload.potensi }}"
        
        # 处理空值
        OUTLET_NAME=${OUTLET_NAME:-""}
        BRAND=${BRAND:-""}
        KECAMATAN=${KECAMATAN:-""}
        POTENSI=${POTENSI:-""}
        
        # 检查是否已存在该shop_code的记录
        if grep -q "^$SHOP_CODE," public/markers.csv; then
          echo "🔄 更新现有记录: $SHOP_CODE"
          # 删除旧记录
          grep -v "^$SHOP_CODE," public/markers.csv > temp.csv
          mv temp.csv public/markers.csv
        else
          echo "➕ 添加新记录: $SHOP_CODE"
        fi
        
        # 添加新记录
        echo "$SHOP_CODE,$LATITUDE,$LONGITUDE,$OUTLET_NAME,$BRAND,$KECAMATAN,$POTENSI" >> public/markers.csv
        
        echo "✅ CSV文件更新完成"
        
        # 显示更新后的文件行数
        LINE_COUNT=$(wc -l < public/markers.csv)
        echo "📊 当前CSV文件总行数: $LINE_COUNT"
        
    - name: 提交更改到仓库
      run: |
        # 检查是否有变更
        if git diff --quiet; then
          echo "📝 没有检测到文件变更"
        else
          echo "💾 检测到文件变更，准备提交"
          git add public/markers.csv
          
          # 创建提交信息
          SHOP_CODE="${{ github.event.client_payload.shop_code }}"
          OUTLET_NAME="${{ github.event.client_payload.outlet_name }}"
          CURRENT_TIME=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          git commit -m "🏪 飞书自动更新: $SHOP_CODE - $OUTLET_NAME

          数据详情:
          - 店铺代码: $SHOP_CODE
          - 经纬度: ${{ github.event.client_payload.latitude }}, ${{ github.event.client_payload.longitude }}
          - 店铺名称: $OUTLET_NAME
          - 品牌: ${{ github.event.client_payload.brand }}
          - 区域: ${{ github.event.client_payload.kecamatan }}
          
          更新时间: $CURRENT_TIME"
          
          git push
          
          echo "✅ 更改已提交并推送到仓库"
        fi
        
    - name: 输出操作结果
      run: |
        echo ""
        echo "🎉 飞书数据处理完成！"
        echo "📍 数据已更新到: public/markers.csv"
        echo "🌐 前端将自动检测到文件变化并刷新地图"
        echo "" 